export const PRIVATE_SOCKET_ACTIONS = {
  WITHDRAW: 'WD',
  DEPOSIT: 'DP',
  NEW_ORDER: 'NO',
  PARTIAL_ORDER: 'PO',
  FILL_ORDER: 'FO',
  CANCEL_ORDER: 'CO',
  APIKEY_CHANGED: 'AK',
  MOBILE_KEY_CHANGED: 'MK',
  VERIFICATION_STATUS: 'VS',
  CONNECT: 'CN',
  RECONNECT: 'RC',
  DISCONNECT: 'DC',
  ANNOUNCEMENT: 'A'
};
