export const CURRENCY_DECIMALS = {
  TRY: 2,
  BTC: 8,
  ETH: 8,
  XLM: 8,
  XRP: 8
};

export const SERVER_ERROR_STATUS_CODES = {
  APPROVED_USERS_CANNOT_ADD_REFERRER: 1027,
  INVALID_REF_CODE: 1028,
  BETA_USER_WARNING: 1050,
  INSTANT_TRADE_PRICE_CHANGED: 1210
};

export const INSTANT_TRADE_CONSTANTS = {
  ROUND_PRICE_DIGITS: 5,
  PRICE_POLLING_INTERVAL: 5000
};
